services:
  # The Notes Microservice
  notes-api:
    build: 
      context: .
      args:
        - PORT=${NOTES_APP_PORT}
    restart: on-failure:5
    # Maps local port (from .env) to the internal container port
    ports:
      - "${NOTES_APP_PORT}:${NOTES_APP_PORT}"
    env_file:
      - .env
    environment:
      - PORT=${NOTES_APP_PORT}
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
      - redis-cache

  # MongoDB Document Store
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  # Redis Cache Layer
  redis-cache:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mongo_data: